import React from 'react';
import { Router, Route, Switch } from 'dva/router';

import dynamic from 'dva/dynamic';
import App from './routes/app';

import KeepAlive, { AliveScope } from 'react-activation'

import LoginPage from './routes/login/index';

import { ConfigProvider } from 'antd';
import zhCN from 'antd/es/locale/zh_CN';

const RouterConfig=({ history,app })=> {
  // 按需加载model
  // eslint-disable-next-line no-sparse-arrays
  const routes=[
    {
      path:'/index',
      name:'IndexPage',
      component:()=>import('./routes/IndexPage')
    },
    {
      path:'/student-manage',
      name:'StudentManage',
      keepalive:true,
      models:()=>[import('./models/person')],
      component:()=>import('./routes/manage/studentManage'),
    },
    {
      path:'/student-detail',
      name:'StudentDetail',
      models:()=>[import('./models/person')],
      component:()=>import('./routes/manage/studentDetail')
    },{
      path:'/teacher-manage',
      name:'TeacherManage',
      keepalive:true,
      models:()=>[import('./models/person')],
      component:()=>import('./routes/manage/teacherManage')
    },{
      path:'/teacher-detail',
      name:'TeacherDetail',
      models:()=>[import('./models/person')],
      component:()=>import('./routes/manage/teacherDetail')
    },{
      path:'/employee-manage',
      name:'EmployeeManage',
      models:()=>[import('./models/person')],
      component:()=>import('./routes/manage/employeeManage')
    },
    {
      path:'/employee-detail',
      name:'EmployeeDetail',
      models:()=>[import('./models/person')],
      component:()=>import('./routes/manage/EmployeeDetail')
    },{
      path:'/grade-manage',
      name:'GradeManage',
      models:()=>[import('./models/grade')],
      component:()=>import('./routes/manage/gradeManage')
    },{
      path:'/class-manage',
      name:'ClassManage',
      models:()=>[import('./models/class')],
      component:()=>import('./routes/manage/classManage')
    },{
      path:'/class-detail',
      name:'ClassDetail',
      models:()=>[import('./models/class')],
      component:()=>import('./routes/manage/classDetail')
    },{
      path:'/class-leader',
      name:'ClassLeaderMange',
      models:()=>[import('./models/classLeader')],
      component:()=>import('./routes/manage/classLeader')
    },{
      path:'/job-manage',
      name:'JobMange',
      models:()=>[import('./models/job')],
      component:()=>import('./routes/manage/jobManage')
    },{
      path:'/job-detail',
      name:'JobDetail',
      models:()=>[import('./models/job')],
      component:()=>import('./routes/manage/jobDetail')
    },{
      path:'/edit-information',
      name:'EditInformation',
      models:()=>[import('./models/information')],
      component:()=>import('./routes/login/editInformation')
    },{
      path:'/build-manage',
      name:'BuildManage',
      models:()=>[import('./models/place')],
      component:()=>import('./routes/placeManage/buildManage')
    },{
      path:'/place-manage',
      name:'PlaceManage',
      models:()=>[import('./models/place')],
      component:()=>import('./routes/placeManage/placeManage')
    },{
      path:'/ground-manage/:buildType',
      name:'GroundManage',
      models:()=>[import('./models/place')],
      component:()=>import('./routes/placeManage/groundManage')
    },{
      path:'/term-manage',
      name:'TermManage',
      models:()=>[import('./models/term')],
      component:()=>import('./routes/termManage/termManage')
    },{
      path:'/new-term',
      name:'NewTerm',
      models:()=>[import('./models/term')],
      component:()=>import('./routes/termManage/newTerm')
    },{
    //   path:'/edit-term/:semesterId',
    //   name:'EditTerm',
    //   models:()=>[import('./models/term')],
    //   component:()=>import('./routes/termManage/editTerm')
    // },{
      path:'/term-edit/:semesterId',
      name:'TermEdit',
      models:()=>[import('./models/term')],
      component:()=>import('./routes/termManage/TermEdit')
    },{
      path:'/grade-setting',
      name:'GradeSet',
      models:()=>[import('./models/term')],
      component:()=>import('./routes/termManage/gradeSet')
    },{
      path:'/schedule-manage',
      name:'ScheduleManage',
      models:()=>[import('./models/schedule')],
      component:()=>import('./routes/scheduleManage/scheduleManage')
    },{
      path:'/schedule-query',
      name:'ScheduleQuery',
      models:()=>[import('./models/schedule')],
      component:()=>import('./routes/scheduleManage/scheduleQuery')
    },{
      path:'/school-calendar-manage',
      name:'SchoolCalendarManage',
      models:()=>[import('./models/term')],
      component:()=>import('./routes/schoolCalendarManage/schoolCalendarManage')
    },{
      path:'/department-manage',
      name:'DepartmentManage',
      models:()=>[import('./models/department')],
      component:()=>import('./routes/manage/departmentManage')
    },{
      path:'/student-style',
      name:'StudentStyle',
      models:()=>[import('./models/classSpace')],
      component:()=>import('./routes/classSpace/studentStyle')
    },{
      path:'/style-detail/:id',
      name:'StyleDetail',
      models:()=>[import('./models/classSpace')],
      component:()=>import('./routes/classSpace/styleDetail')
    },{
      path:'/style-statistics-list',
      name:'StatisticsList',
      models:()=>[import('./models/classSpace')],
      component:()=>import('./routes/classSpace/statisticsList')
    },{
      path:'/salary-manage',
      name:'SalaryManage',
      models:()=>[import('./models/salary')],
      component:()=>import('./routes/salaryManage/salaryManage')
    },{
      path:'/add-salary',
      name:'AddSalary',
      models:()=>[import('./models/salary')],
      component:()=>import('./routes/salaryManage/addSalary')
    },{
      path:'/salary-detail',
      name:'SalaryDetail',
      models:()=>[import('./models/salary')],
      component:()=>import('./routes/salaryManage/salaryDetail')
    },{
      path:'/upload-staff',
      name:'UploadStaff',
      models:()=>[import('./models/person')],
      component:()=>import('./routes/manage/uploadStaff')
    },{
      path:'/account-manage',
      name:'AccountManage',
      models:()=>[import('./models/setting')],
      component:()=>import('./routes/setting/accountManage')
    },{
      path:'/account-detail/:userId',
      name:'AccountDetail',
      models:()=>[import('./models/setting')],
      component:()=>import('./routes/setting/accountDetail')
    },{
      path:'/role-access',
      name:'RoleAccess',
      models:()=>[import('./models/setting')],
      component:()=>import('./routes/setting/roleAccess')
    },{
      path:'/access-detail/:jobId',
      name:'AccessDetail',
      models:()=>[import('./models/setting')],
      component:()=>import('./routes/setting/accessDetail')
    },{
      path:'/upload-student',
      name:'UploadStudents',
      models:()=>[import('./models/person')],
      component:()=>import('./routes/manage/uploadStudents')
    },{
      path:'/upload-teacher',
      name:'UploadTeacher',
      models:()=>[import('./models/class')],
      component:()=>import('./routes/manage/uploadTeacher')
    },{
      path:'/upload-grade',
      name:'UploadGrade',
      models:()=>[import('./models/grade')],
      component:()=>import('./routes/manage/uploadGrade')
    },{
      path:'/upload-classes',
      name:'UploadClass',
      models:()=>[import('./models/class')],
      component:()=>import('./routes/manage/uploadClass')
    },{
      path:'/leave-manage',
      name:'LeaveIndex',
      models:()=>[import('./models/leave')],
      component:()=>import('./routes/leaveManage/leaveIndex')
    },{
      path:'/leave-detail',
      name:'LeaveDetail',
      models:()=>[import('./models/leave')],
      component:()=>import('./routes/leaveManage/leaveDetail')
    },{
      path:'/leave-type',
      name:'LeaveType',
      models:()=>[import('./models/leave')],
      component:()=>import('./routes/leaveManage/leaveType')
    },{
      path:'/add-leave-type',
      name:'AddLeaveType',
      models:()=>[import('./models/leave')],
      component:()=>import('./routes/leaveManage/addLeaveType')
    },{
      path:'/examine-rules',
      name:'leaveRuleList',
      models:()=>[import('./models/leave')],
      component:()=>import('./routes/leaveManage/leaveRuleList')
    },{
      path:'/add-leave-rule',
      name:'AddLeaveRule',
      models:()=>[import('./models/leave')],
      component:()=>import('./routes/leaveManage/addLeaveRule')
    },{
      path:'/room-manage',
      name:'RoomIndex',
      models:()=>[import('./models/room')],
      component:()=>import('./routes/roomApply/roomIndex')
    },{
      path:'/room-apply-detail',
      name:'RoomApplyDetail',
      models:()=>[import('./models/room')],
      component:()=>import('./routes/roomApply/roomApplyDetail')
    },{
      path:'/repair-manage',
      name:'RepairIndex',
      models:()=>[import('./models/repair')],
      component:()=>import('./routes/repairManage/repairIndex')
    },{
      path:'/repair-type',
      name:'RepairTypeList',
      models:()=>[import('./models/repair')],
      component:()=>import('./routes/repairManage/repairTypeList')
    },{
      path:'/repair-apply-detail',
      name:'RepairApplyDetail',
      models:()=>[import('./models/repair')],
      component:()=>import('./routes/repairManage/repairApplyDetail')
    },{
      path:'/open-card',
      name:'CardsIndex',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/personCards/cardsIndex')
    },{
      path:'/upload-card',
      name:'UploadCard',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/personCards/uploadCard')
    },{
      path:'/class-notice',
      name:'ClassInformationIndex',
      models:()=>[import('./models/classNotice')],
      component:()=>import('./routes/classInformation/classInformationIndex')
    },{
      path:'/class-notice-detail',
      name:'ClassNoticeDetail',
      models:()=>[import('./models/classNotice')],
      component:()=>import('./routes/classInformation/classNoticeDetail')
    },{
      path:'/card-manage',
      name:'CardManage',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/cardManage')
    },{
      path:'/st-recharge-detail',
      name:'STRechargeDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/stRechargeDetail')
    },{
      path:'/sx-recharge-detail',
      name:'SXRechargeDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/sxRechargeDetail')
    },{
      path:'/st-customer-consume-detail',
      name:'STCustomerConsumeDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/stCustomerConsumeDetail')
    },{
      path:'/sx-customer-consume-detail',
      name:'SXCustomerConsumeDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/sxCustomerConsumeDetail')
    },{
      path:'/customer-circle-detail',
      name:'CustomerCircleDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/customerCircleDetail')
    },{
      path:'/st-ic-circle-detail',
      name:'StIcCircleDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/stIcCircleDetail')
    },{
      path:'/sx-ic-circle-detail',
      name:'SxIcCircleDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/sxIcCircleDetail')
    },{
      path:'/st-ic-consume-detail',
      name:'StIcConsumeDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/stIcConsumeDetail')
    },{
      path:'/sx-ic-consume-detail',
      name:'SxIcConsumeDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/sxIcConsumeDetail')
    },{
      path:'/yks-recharge-detail',
      name:'YKSRechargeDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/yksRechargeDetail')
    },{
      path:'/yks-customer-circle-detail',
      name:'YKSCustomerCircleDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/yksCustomerCircleDetail')
    },{
      path:'/yks-consume-detail',
      name:'YKSCustomerConsumeDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/yksConsumeDetail')
    },{
      path:'/yks-ic-consume-detail',
      name:'YksIcConsumeDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/yksIcConsumeDetail')
    },{
      path:'/yks-ic-circle-detail',
      name:'YksIcCircleDetail',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/yksIcCircleDetail')
    },{ // 天四消费概况
      path:'/consume-record',
      name:'ConsumeRecord',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/cardManage/consumeRecord')
    },{
      path:'/student-evaluation',
      name:'StudentEvaluation',
      models:()=>[import('./models/evaluation')],
      component:()=>import('./routes/studentEvaluation/studentEvaluation')
    },{
      path:'/essential-list/:id',
      name:'EssentialList',
      models:()=>[import('./models/evaluation')],
      component:()=>import('./routes/studentEvaluation/essentialList')
    },{
      path:'/new-template',
      name:'NewTemplate',
      models:()=>[import('./models/evaluation')],
      component:()=>import('./routes/studentEvaluation/newTemplate')
    },{
      path:'/essential-manage/:id',
      name:'EssentialManage',
      models:()=>[import('./models/evaluation')],
      component:()=>import('./routes/studentEvaluation/essentialManage')
    },{
      path:'/edit-point/:id',
      name:'EditPoint',
      models:()=>[import('./models/evaluation')],
      component:()=>import('./routes/studentEvaluation/editPoint')
    },{
      path:'/addPoint/:id',
      name:'AddPoint',
      models:()=>[import('./models/evaluation')],
      component:()=>import('./routes/studentEvaluation/addPoint')
    },{
      path:'/edit-template/:id',
      name:'EditTemplate',
      models:()=>[import('./models/evaluation')],
      component:()=>import('./routes/studentEvaluation/editTemplate')
    },{
      path:'/canteen-menu',
      name:'CanteenMenuList',
      models:()=>[import('./models/canteenMenu')],
      component:()=>import('./routes/canteenMenu/canteenMenuList')
    },{
      path:'/add-canteen-menu',
      name:'AddCanteenMenu',
      models:()=>[import('./models/canteenMenu')],
      component:()=>import('./routes/canteenMenu/addCanteenMenu')
    },{
      path:'/subject-manage',
      name:'SubjectList',
      models:()=>[import('./models/subject')],
      component:()=>import('./routes/subjectManage/subjectList')
    },{
      path:'/add-subject',
      name:'AddSubject',
      models:()=>[import('./models/subject')],
      component:()=>import('./routes/subjectManage/addSubject')
    },{
      path:'/leave-btns',
      name:'leaveRule',
      models:()=>[import('./models/leave')],
      component:()=>import('./components/leaveRule')
    },{
      path:'/student-leave',
      name:'studentLeave',
      models:()=>[import('./models/studentLeave')],
      component:()=>import('./routes/studentLeave/studentLeave')
    },{
      path:'/student-leave-detail/:id',
      name:'studentLeaveDetail',
      models:()=>[import('./models/studentLeave')],
      component:()=>import('./routes/studentLeave/studentLeaveDetail')
    },{
      path:'/type-manage',
      name:'typeManage',
      models:()=>[import('./models/studentLeave')],
      component:()=>import('./routes/studentLeave/typeManage')
    },{
      path:'/approver-setting',
      name:'approverSetting',
      models:()=>[import('./models/studentLeave')],
      component:()=>import('./routes/studentLeave/approverSetting')
    },{
      path:'/class-score',
      name:'ClassScoreIndex',
      models:()=>[import('./models/classScore')],
      component:()=>import('./routes/classScore/classScoreIndex')
    },{
      path:'/class-score-type-detail',
      name:'ClassScoreTypeDetail',
      models:()=>[import('./models/classScore')],
      component:()=>import('./routes/classScore/classScoreTypeDetail')
    },{
      path:'/visit-list',
      name:'VisitList',
      models:()=>[import('./models/visit')],
      component:()=>import('./routes/visitManage/visitList')
    },{
      path:'/room-notice-list',
      name:'RoomNoticeList',
      models:()=>[import('./models/roomNotice')],
      component:()=>import('./routes/roomNotice/roomNoticeList')
    },{
      path:'/set-room-notice',
      name:'SetRoomNotice',
      models:()=>[import('./models/roomNotice')],
      component:()=>import('./routes/roomNotice/setRoomNotice')
    },{
      path:'/update-room-notice',
      name:'UpdateRoomNotice',
      models:()=>[import('./models/roomNotice')],
      component:()=>import('./routes/roomNotice/updateRoomNotice')
    },{
      path:'/ssw-position-list',
      name:'SswPositionList',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswPositionList')
    },{
      path:'/association-class-manage',
      name:'AssociationClassManage',
      models:()=>[import('./models/association')],
      component:()=>import('./routes/classManage/associationClassManage')
    },{
      path:'/association-class-config',
      name:'AssociationClassConfig',
      models:()=>[import('./models/association')],
      component:()=>import('./routes/classManage/associationClassConfig')
    }
    ,{
      path:'/new-association-class-config',
      name:'NewAssociationClassConfig',
      models:()=>[import('./models/association'), import('./models/schedule')],
      component:()=>import('./routes/classManage/newAssociationClassConfig')
    } ,{
      path:'/edit-association-class-config/:id',
      name:'EditAssociationClassConfig',
      models:()=>[import('./models/association'), import('./models/schedule')],
      component:()=>import('./routes/classManage/editAssociationClassConfig')
    }
    ,{
      path:'/association-class-statistics',
      name:'AssociationClassStatistics',
      models:()=>[import('./models/association'), import('./models/schedule')],
      component:()=>import('./routes/classManage/associationClassStatistics')
    },{
      path:'/statistics-detail/:id',
      name:'StatisticsDetail',
      models:()=>[import('./models/association'), import('./models/schedule')],
      component:()=>import('./routes/classManage/statisticsDetail')
    }
    ,{
      path:'/ssw-person-mac',
      name:'SswPersonMacIndex',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswPersonMac/sswPersonMacIndex')
    },{
      path:'/bind-student-mac',
      name:'BindStudentMac',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswPersonMac/bindStudentMac')
    },{
      path:'/bind-teacher-mac',
      name:'BindTeacherMac',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswPersonMac/bindTeacherMac')
    },{
      path:'/bind-staff-mac',
      name:'BindStaffMac',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswPersonMac/bindStaffMac')
    },{
      path:'/ssw-wrist-status',
      name:'SswWristStatus',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswWristStatus')
    },{
      path:'/ssw-wrist-data',
      name:'SswWristDataIndex',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswWristData/sswWristDataIndex')
    },{
      path:'/ssw-wrist-message',
      name:'SswMessageList',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswWristSendMsg/sswWristMessageList')
    },{
      path:'/ssw-wrist-message-detail',
      name:'SswMessageDetail',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswWristSendMsg/sswWristMessageDetail')
    },{
      path:'/add-group-send-msg',
      name:'AddGroupSendMsg',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswWristSendMsg/addGroupSend')
    },{
      path:'/add-person-send-msg',
      name:'AddPersonSendMsg',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/sswWristSendMsg/addPersonSend')
    },{
      path:'/bluetooth-attend-list',
      name:'BlueTootnAttendIndex',
      models:()=>[import('./models/sswWristband')],
      component:()=>import('./routes/sswWristband/blueTooth/blueToothAttend')
    }
    ,{
      path:'/trust-manage',
      name:'TrustManage',
      models:()=>[import('./models/trustManage')],
      component:()=>import('./routes/trustManage/trustManage')
    },{
      path:'/new-trust',
      name:'NewTrust',
      models:()=>[import('./models/trustManage')],
      component:()=>import('./routes/trustManage/newTrust')
    },{
      path:'/edit-trust/:id',
      name:'EditTrust',
      models:()=>[import('./models/trustManage')],
      component:()=>import('./routes/trustManage/editTrust')
    },{
      path:'/record-detail',
      name:'RecordDetail',
      models:()=>[import('./models/trustManage')],
      component:()=>import('./routes/trustManage/recordDetail')
    },{
      path:'/school-brief',
      name:'SchoolBrief',
      models:()=>[import('./models/information'), import('./models/dataScreem')],
      component:()=>import('./routes/login/schoolBrief')
    },{
      path:'/material-list',
      name:'MaterialList',
      models:()=>[import('./models/material')],
      component:()=>import('./routes/materialManage/materialList')
    },{
      path:'/material-detail/:id',
      name:'MaterialDetail',
      models:()=>[import('./models/material')],
      component:()=>import('./routes/materialManage/materialDetail')
    },{
      path:'/material-menu-manage',
      name:'MaterialMenuManage',
      models:()=>[import('./models/material')],
      component:()=>import('./routes/materialManage/materialMenuManage')
    },{
      path:'/score-manage',
      name:'ScoreManage',
      models:()=>[import('./models/studentScore')],
      component:()=>import('./routes/scoreManage/scoreManage')
    },{
      path:'/add-studentScore',
      name:'AddStudentScore',
      models:()=>[import('./models/studentScore')],
      component:()=>import('./routes/scoreManage/addStudentScore')
    },{
      path:'/score-detail',
      name:'ScoreDetail',
      models:()=>[import('./models/studentScore')],
      component:()=>import('./routes/scoreManage/scoreDetail')
    },{
      path:'/student-swipe-card',
      name:'SwipeCards',
      models:()=>[import('./models/studentSwipeCard')],
      component:()=>import('./routes/studentSwipeCard/swipeCard')
    },{
      path:'/role-access-student',
      name:'RoleAccessStudent',
      models:()=>[import('./models/setting')],
      component:()=>import('./routes/setting/roleAccessStudent')
    },{
      path:'/access-detail-student/:jobId',
      name:'AccessDetailStudent',
      models:()=>[import('./models/setting')],
      component:()=>import('./routes/setting/accessDetailStudent')
    },{
      path:'/style-manage',
      name:'StyleManage',
      models:()=>[import('./models/styleManage')],
      component:()=>import('./routes/styleManage/styleList')
    },{
      path:'/add-style',
      name:'AddStyle',
      models:()=>[import('./models/styleManage')],
      component:()=>import('./routes/styleManage/addStyle')
    },{
      path:'/school-notice-list',
      name:'SchoolNoticeList',
      models:()=>[import('./models/schoolNotice')],
      component:()=>import('./routes/schoolNotice/schoolNoticeList')
    },{
      path:'/add-school-notice',
      name:'AddSchoolNotice',
      models:()=>[import('./models/schoolNotice')],
      component:()=>import('./routes/schoolNotice/addSchoolNotice')
    },{
      path:'/set-teacher-hander',
      name:'SetTeacherHander',
      models:()=>[import('./models/schoolNotice')],
      component:()=>import('./routes/schoolNotice/setTeacherHander')
    },{
      path:'/didano-device-list',
      name:'DeviceList',
      models:()=>[import('./models/didano')],
      component:()=>import('./routes/didano/deviceList')
    },{
      path:'/didano-sync',
      name:'DidanoSync',
      models:()=>[import('./models/didano')],
      component:()=>import('./routes/didano/didanoSync')
    },{
      path:'/student-takeaway-list',
      name:'StudentTakeawayList',
      models:()=>[import('./models/didano')],
      component:()=>import('./routes/didano/studentTakeawayList')
    },{
      path:'/didano-detection-list',
      name:'DidanoDetectionList',
      models:()=>[import('./models/didano')],
      component:()=>import('./routes/didano/didanoDetectionList')
    },{
      path:'/card-list',
      name:'CardList',
      models:()=>[import('./models/banCard')],
      component:()=>import('./routes/banCard/cardList')
    },{
      path:'/card-config',
      name:'CardConfig',
      models:()=>[import('./models/banCard')],
      component:()=>import('./routes/banCard/cardConfig')
    },{
      path:'/evaluation-manage',
      name:'EvaluationManage',
      models:()=>[import('./models/teacherEvaluation')],
      component:()=>import('./routes/teacherEvaluation/evaluationManage')
    },{
      path:'/evaluation-of-type-detail',
      name:'EvaluationOfTypeDetail',
      models:()=>[import('./models/teacherEvaluation')],
      component:()=>import('./routes/teacherEvaluation/evaluationOfTypeDetail')
    },{
      path:'/template-manage',
      name:'TempalateManage',
      models:()=>[import('./models/teacherEvaluation')],
      component:()=>import('./routes/teacherEvaluation/tempalateManage')
    },{
      path:'/evaluation-statistics',
      name:'EvaluationStatistics',
      models:()=>[import('./models/teacherEvaluation')],
      component:()=>import('./routes/teacherEvaluation/evaluationStatistics')
    },{
      path:'/evaluation-statistics-detail',
      name:'evaluationStatisticsDetail',
      models:()=>[import('./models/teacherEvaluation')],
      component:()=>import('./routes/teacherEvaluation/statisticsDetail')
    },{
      path:'/student-score',
      name:'StudentScore',
      models:()=>[import('./models/person'), import('./models/score')],
      component:()=>import('./routes/studentScore/studentScore')
    },{
      path:'/score-rule',
      name:'ScoreRule',
      models:()=>[import('./models/person'), import('./models/score')],
      component:()=>import('./routes/studentScore/scoreRule')
    },{
      path:'/score-level',
      name:'ScoreLevel',
      models:()=>[import('./models/person'), import('./models/score')],
      component:()=>import('./routes/studentScore/scoreLevel')
    },{
      path:'/score-history',
      name:'ScoreHistory',
      models:()=>[import('./models/person'), import('./models/score')],
      component:()=>import('./routes/studentScore/scoreHistory')
    },{
      path:'/student-medal',
      name:'StudentMedal',
      models:()=>[import('./models/person'), import('./models/score')],
      component:()=>import('./routes/studentScore/studentMedal')
    },{
      path:'/medal-manage',
      name:'MedalManage',
      models:()=>[import('./models/person'), import('./models/score')],
      component:()=>import('./routes/studentScore/medalManage')
    },{
      path:'/score-goods',
      name:'ScoreGoods',
      models:()=>[import('./models/person'), import('./models/score')],
      component:()=>import('./routes/studentScore/scoreGoods')
    },{
      path:'/score-goods-histroy',
      name:'ScoreGoodsHistory',
      models:()=>[import('./models/person'), import('./models/score')],
      component:()=>import('./routes/studentScore/scoreGoodsHistory')
    },{
      path:'/add-goods',
      name:'AddGoods',
      models:()=>[import('./models/person'), import('./models/score')],
      component:()=>import('./routes/studentScore/addGoods')
    },{
      path:'/edit-goods',
      name:'EditGoods',
      models:()=>[import('./models/person'), import('./models/score')],
      component:()=>import('./routes/studentScore/editGoods')
    },{
      path:'/student-honor',
      name:'StudentHonor',
      models:()=>[import('./models/person'), import('./models/honor')],
      component:()=>import('./routes/studentHonor/studentHonor')
    },{
      path:'/person-honor-level',
      name:'PersonHonorLevel',
      models:()=>[import('./models/person'), import('./models/honor')],
      component:()=>import('./routes/studentHonor/personHonorLevel')
    },{
      path:'/person-honor-records',
      name:'PersonHonorRecords',
      models:()=>[import('./models/person'), import('./models/honor')],
      component:()=>import('./routes/studentHonor/personHonorRecords')
    },{
      path:'/honor-detail',
      name:'HonorDetail',
      models:()=>[import('./models/person'), import('./models/honor')],
      component:()=>import('./routes/studentHonor/honorDetail')
    },{
      path:'/questionnaire-list',
      name:'QuestionnaireList',
      models:()=>[import('./models/questionnaire')],
      component:()=>import('./routes/questionnaire/questionnaireList')
    },{
      path:'/new-questionnaire',
      name:'newQuestionnaire',
      models:()=>[import('./models/questionnaire')],
      component:()=>import('./routes/questionnaire/newQuestionnaire')
    },{
      path:'/edit-questionnaire/:id',
      name:'editQuestionnaire',
      models:()=>[import('./models/questionnaire')],
      component:()=>import('./routes/questionnaire/editQuestionnaire')
    },{
      path:'/student-portrait-manage',
      name:'studentPortraitManage',
      models:()=>[import('./models/portrait')],
      component:()=>import('./routes/portraitManage/studentPortraitManage')
    },{
      path:'/teacher-portrait-manage',
      name:'teacherPortraitManage',
      models:()=>[import('./models/portrait')],
      component:()=>import('./routes/portraitManage/teacherPortraitManage')
    },{
      path:'/staff-portrait-manage',
      name:'staffPortraitManage',
      models:()=>[import('./models/portrait')],
      component:()=>import('./routes/portraitManage/staffPortraitManage')
    },{
      path:'/student-portrait-reg',
      name:'studentPortraitReg',
      models:()=>[import('./models/portrait')],
      component:()=>import('./routes/portraitManage/studentPortraitReg')
    },{
      path:'/teacher-portrait-reg',
      name:'teacherPortraitReg',
      models:()=>[import('./models/portrait')],
      component:()=>import('./routes/portraitManage/teacherPortraitReg')
    },{
      path:'/staff-portrait-reg',
      name:'staffPortraitReg',
      models:()=>[import('./models/portrait')],
      component:()=>import('./routes/portraitManage/staffPortraitReg')
    },{
      path:'/sync-records',
      name:'syncRecords',
      models:()=>[import('./models/syncRecords')],
      component:()=>import('./routes/ydjSync/syncRecords')
    },{
      path:'/news-information',
      name:'EducationInformation',
      models:()=>[import('./models/newsInformation')],
      component:()=>import('./routes/newsInformation/educationInformation')
    },{
      path:'/add-news',
      name:'AddNews',
      models:()=>[import('./models/newsInformation')],
      component:()=>import('./routes/newsInformation/addNews')
    },{
      path:'/moral-index',
      name:'MoralIndex',
      models:()=>[import('./models/moralEvaluation')],
      component:()=>import('./routes/moralEvaluation/moralIndex')
    },{
      path:'/moral-type-detail',
      name:'MoralTypeDetail',
      models:()=>[import('./models/moralEvaluation')],
      component:()=>import('./routes/moralEvaluation/moralTypeDetail')
    },{
      path:'/set-flag',
      name:'SetFlag',
      models:()=>[import('./models/moralEvaluation')],
      component:()=>import('./routes/moralEvaluation/setFlag')
    },{
      path:'/filed-list',
      name:'FiledList',
      models:()=>[import('./models/filePersons')],
      component:()=>import('./routes/filePersons/filedList')
    },{
      path:'/filed-record',
      name:'FiledRecord',
      models:()=>[import('./models/filePersons')],
      component:()=>import('./routes/filePersons/filedRecord')
    },{
      path:'/goOut-training',
      name:'Train',
      models:()=>[import('./models/train')],
      component:()=>import('./routes/goOutTraining/train')
    },{
      path:'/train-detail',
      name:'TrainDetail',
      models:()=>[import('./models/train')],
      component:()=>import('./routes/goOutTraining/trainDetail')
    },{
      path:'/idea-feedback',
      name:'FeedbackList',
      models:()=>[import('./models/ideaFeedback')],
      component:()=>import('./routes/ideaFeedback/feedbackList')
    },{
      path:'/opinion-type-management',
      name:'IdeaType',
      models:()=>[import('./models/ideaFeedback')],
      component:()=>import('./routes/ideaFeedback/ideaType')
    },{
      path:'/student-binding',
      name:'StudentBinding',
      models:()=>[import('./models/userBinding')],
      component:()=>import('./routes/userBinding/studentBinding')
    },{
      path:'/teacher-binding',
      name:'TeacherBinding',
      models:()=>[import('./models/userBinding')],
      component:()=>import('./routes/userBinding/teacherBinding')
    },{
      path:'/employee-binding',
      name:'EmployeeBinding',
      models:()=>[import('./models/userBinding')],
      component:()=>import('./routes/userBinding/employeeBinding')
    },{
      path:'/beneficial-coin',
      name:'CoinManage',
      models:()=>[import('./models/beneficialCoin')],
      component:()=>import('./routes/beneficialCoin/coinManage')
    },{
      path:'/coin-classDetail',
      name:'CoinClassDetail',
      models:()=>[import('./models/beneficialCoin')],
      component:()=>import('./routes/beneficialCoin/coinClassDetail')
    },{
      path:'/teacher-property',
      name:'TeacherProperty',
      models:()=>[import('./models/beneficialCoin')],
      component:()=>import('./routes/beneficialCoin/teacherProperty')
    },{
      // 宇泛人脸注册管理
      path:'/student-face-reg',
      name:'StudentFaceReg',
      models:()=>[import('./models/faceManage')],
      component:()=>import('./routes/faceManage/studentFaceReg')
    },{
      path:'/teacher-face-reg',
      name:'TeacherFaceReg',
      models:()=>[import('./models/faceManage')],
      component:()=>import('./routes/faceManage/teacherFaceReg')
    },{
      path:'/staff-face-reg',
      name:'StaffFaceReg',
      models:()=>[import('./models/faceManage')],
      component:()=>import('./routes/faceManage/staffFaceReg')
    },{
      path:'/facility-manage',
      name:'FacilityManage',
      models:()=>[import('./models/faceManage')],
      component:()=>import('./routes/faceManage/facilityManage')
    },{
      path:'/authorize-manage',
      name:'AuthorizeManage',
      models:()=>[import('./models/faceManage')],
      component:()=>import('./routes/faceManage/authorizeManage')
    },{
      path:'/unauth-person',
      name:'UnauthPerson',
      models:()=>[import('./models/faceManage')],
      component:()=>import('./routes/faceManage/unauthPerson')
    },{
      // 宇泛人脸注册管理-wo平台
      path:'/wo-student-face-reg',
      name:'WoStudentFaceReg',
      models:()=>[import('./models/woFaceManage')],
      component:()=>import('./routes/woFaceManage/woStudentFaceReg')
    },{
      path:'/wo-teacher-face-reg',
      name:'WoTeacherFaceReg',
      models:()=>[import('./models/woFaceManage')],
      component:()=>import('./routes/woFaceManage/woTeacherFaceReg')
    },{
      path:'/wo-staff-face-reg',
      name:'WoStaffFaceReg',
      models:()=>[import('./models/woFaceManage')],
      component:()=>import('./routes/woFaceManage/woStaffFaceReg')
    },{
      path:'/wo-facility-manage',
      name:'WoFacilityManage',
      models:()=>[import('./models/woFaceManage')],
      component:()=>import('./routes/woFaceManage/woFacilityManage')
    },{
      path:'/wo-authorize-manage',
      name:'WoAuthorizeManage',
      models:()=>[import('./models/woFaceManage')],
      component:()=>import('./routes/woFaceManage/woAuthorizeManage')
    },{
      path:'/wo-unauth-person',
      name:'WoUnauthPerson',
      models:()=>[import('./models/woFaceManage')],
      component:()=>import('./routes/woFaceManage/woUnauthPerson')
    },{
      path:'/term-message',
      name:'TermMessage',
      models:()=>[import('./models/synthesizeEvaluation')],
      component:()=>import('./routes/synthesizeEvaluation/termmessage')
    },{
      path:'/subject-score',
      name:'SubjectScore',
      models:()=>[import('./models/synthesizeEvaluation')],
      component:()=>import('./routes/synthesizeEvaluation/subjectScore')
    },{
      path:'/student-report',
      name:'StudentReport',
      models:()=>[import('./models/synthesizeEvaluation')],
      component:()=>import('./routes/synthesizeEvaluation/studentReport')
    },{
      path:'/report-query',
      name:'ReportQuery',
      models:()=>[import('./models/synthesizeEvaluation')],
      component:()=>import('./routes/synthesizeEvaluation/reportQuery')
    },{
      path:'/check-progress',
      name:'CheckProgress',
      models:()=>[import('./models/synthesizeEvaluation')],
      component:()=>import('./routes/synthesizeEvaluation/checkProgress')
    },{
      path:'/evaluation-template',
      name:'EvaluationTemplate',
      models:()=>[import('./models/synthesizeEvaluation')],
      component:()=>import('./routes/synthesizeEvaluation/evaluationTemplate')
    },{
      path:'/add-template',
      name:'AddTemplate',
      models:()=>[import('./models/synthesizeEvaluation')],
      component:()=>import('./routes/synthesizeEvaluation/addTemplate')
    },{
      path:'/level-set',
      name:'LevelSet',
      models:()=>[import('./models/synthesizeEvaluation')],
      component:()=>import('./routes/synthesizeEvaluation/levelSet')
    },{
      path:'/evaluation-template-manage',
      name:'ShowTemplate',
      models:()=>[import('./models/synthesizeEvaluation')],
      component:()=>import('./routes/synthesizeEvaluation/ShowTemplate')
    },{
      path:'/oa-template-list',
      name:'OaTemplateList',
      models:()=>[import('./models/oa')],
      component:()=>import('./routes/oaManage/oaTemplateList')
    },{
      path:'/new-OaTemplate',
      name:'NewOaTemplate',
      models:()=>[import('./models/oa')],
      component:()=>import('./routes/oaManage/newOaTemplate')
    },{
      path:'/edit-OaTemplate/:id',
      name:'EditOaTemplate',
      models:()=>[import('./models/oa')],
      component:()=>import('./routes/oaManage/editOaTemplate')
    },{
      path:'/oa-record-list',
      name:'OaRecordList',
      models:()=>[import('./models/oa')],
      component:()=>import('./routes/oaManage/oaRecordList')
    },{
      path:'/oa-record-detail/:id',
      name:'OaRecordsDetail',
      models:()=>[import('./models/oa')],
      component:()=>import('./routes/oaManage/oaRecordsDetail')
    },{
      path:'/dstm-list',
      name:'DstmList',
      models:()=>[import('./models/dstm')],
      component:()=>import('./routes/dstm/DstmList')
    },{
      path:'/new-dstm',
      name:'NewDstm',
      models:()=>[import('./models/dstm')],
      component:()=>import('./routes/dstm/NewDstm')
    },{
      path:'/dstm-detail',
      name:'DstmDetail',
      models:()=>[import('./models/dstm')],
      component:()=>import('./routes/dstm/DstmDetail')
    },{
      path:'/edit-dstm',
      name:'EditDstm',
      models:()=>[import('./models/dstm')],
      component:()=>import('./routes/dstm/EditDstm')
    },
    {
      path:'/asset-info',
      name:'AssetInfo',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/assetInfo')
    },{
      path:'/add-assetsType',
      name:'AddAssetsType',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/addAssetsType')
    },{
      path:'/import-asset-info',
      name:'ImportAssetInfo',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/importAssetInfo')
    },{
      path:'/asset-types',
      name:'AssetTypes',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/assetTypes')
    },{
      path:'/unit-manage',
      name:'UnitManage',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/unitManage')
    },{
      path:'/asset-query',
      name:'AssetQuery',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/assetQuery')
    },{
      path:'/goods-apply',
      name:'GoodsApply',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/goodsApply')
    },{
      path:'/assets-apply-detail',
      name:'AssetsDetail',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/assetsDetail')
    },{
      path:'/handler-set',
      name:'HandlerSet',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/handlerSet')
    },{
      path:'/goods-purchase',
      name:'GoodsPurchase',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/goodsPurchase')
    },{
      path:'/goods-purchase-detail',
      name:'PurchaseDetail',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/purchaseDetail')
    },{
      path:'/auditor-set',
      name:'AuditorSet',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/auditorSet')
    },{
      path:'/assets-list',
      name:'AssetsList',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/assetsList')
    },{
      path:'/stock-record',
      name:'StockRecord',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/stockRecord')
    },{
      path:'/asset-transfer',
      name:'AssetTransfer',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/assetTransfer')
    },{
      path:'/asset-allocation',
      name:'AssetAllocation',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/assetAllocation')
    },{
      path:'/asset-increase',
      name:'AssetIncrease',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/assetIncrease')
    },{
      path:'/batch-increase',
      name:'BatchIncrease',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/batchIncrease')
    },{
      path:'/add-increase',
      name:'AddIncrease',
      models:()=>[import('./models/assetsManage')],
      component:()=>import('./routes/assetsManage/addIncrease')
    },{
      path:'/set-screen',
      name:'SetScreen',
      models:()=>[import('./models/bigScreen')],
      component:()=>import('./routes/bigScreen/setScreen')
    },{
      path:'/screen-list',
      name:'ScreenList',
      models:()=>[import('./models/bigScreen')],
      component:()=>import('./routes/bigScreen/ScreenList')
    },{
      path:'/new-screen',
      name:'NewScreen',
      models:()=>[import('./models/bigScreen')],
      component:()=>import('./routes/bigScreen/newScreen')
    },{
      path:'/staff-attendance',
      name:'AttendanceList',
      models:()=>[import('./models/staffAttendance')],
      component:()=>import('./routes/staffAttendance/attendanceList')
    },{
      path:'/temperature-check',
      name:'TemperatureQuery',
      models:()=>[import('./models/temperatureCheck')],
      component:()=>import('./routes/temperatureCheck/temperatureQuery')
    },{
      path:'/class-manage-info',
      name:'ClassManageInfo',
      models:()=>[import('./models/leaveSchoolManage')],
      component:()=>import('./routes/leaveSchoolManage/ClassManageInfo')
    },{
      path:'/student-management',
      name:'StudentManagement',
      models:()=>[import('./models/leaveSchoolManage')],
      component:()=>import('./routes/leaveSchoolManage/studentManagement')
    },{
      path:'/leave-school-record',
      name:'LeaveSchocolRecord',
      models:()=>[import('./models/leaveSchoolManage')],
      component:()=>import('./routes/leaveSchoolManage/leaveSchoolRecord')
    },{
      path:'/person-info-list',
      name:'PersonInfoList',
      models:()=>[import('./models/kindergartenManage')],
      component:()=>import('./routes/kindergartenManage/personInfoList')
    },{
      path:'/test-report-list',
      name:'TestReportList',
      models:()=>[import('./models/kindergartenManage')],
      component:()=>import('./routes/kindergartenManage/testReportList')
    },{
      path:'/test-report-detail',
      name:'TestReportDetail',
      models:()=>[import('./models/kindergartenManage')],
      component:()=>import('./routes/kindergartenManage/testReportDetail')
    },{
      path:'/monitor-list',
      name:'MonitorList',
      models:()=>[import('./models/monitor')],
      component:()=>import('./routes/monitor/monitorList')
    },{
      path:'/monitor-detail',
      name:'MonitorDetail',
      models:()=>[import('./models/monitor')],
      component:()=>import('./routes/monitor/monitorDetail')
    },{
      path:'/handhold-list',
      name:'HandholdList',
      models:()=>[import('./models/handhold')],
      component:()=>import('./routes/handholdDevice/handholdList')
    },{
      path:'/handheld-statistical',
      name:'HandheldStatistical',
      models:()=>[import('./models/handhold')],
      component:()=>import('./routes/handholdDevice/handheldStatistical')
    },{
      path:'/parents-card',
      name:'ParentsCard',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/parentsCardManage/parentsCard')
    },{
      path:'/upload-parents-card',
      name:'UploadParentsCard',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/parentsCardManage/uploadParentsCard')
    },{
      path:'/parents-card-manage',
      name:'ParentsCardManage',
      models:()=>[import('./models/card')],
      component:()=>import('./routes/parentsCardManage/parentsCardManage')
    },{
      path:'/kindergarten-setting',
      name:'KindergartenSetting',
      models:()=>[import('./models/kindergarten'), import('./models/studentLeave')],
      component:()=>import('./routes/kindergartenSetting/kindergartenSetting')
    },{
      path:'/record-type',
      name:'RecordTypeList',
      models:()=>[import('./models/recordType')],
      component:()=>import('./routes/recordType/recordTypeList')
    },{
      path:'/relateEntry-setting',
      name:'RelateEntrySetting',
      models:()=>[import('./models/relateEntry')],
      component:()=>import('./routes/relateEntrySetting/relateEntrySetting')
    },{
      path:'/aerial-view',
      name:'AerialView',
      models:()=>[import('./models/dataScreem')],
      component:()=>import('./routes/dataScreem/aerialView')
    },{
      path:'/device-manage',
      name:'DeviceManage',
      models:()=>[import('./models/dataScreem')],
      component:()=>import('./routes/dataScreem/deviceManage')
    },

    {
      path:'/parent-manage',
      name:'ParentMange',
      models:()=>[import('./models/parent')],
      component:()=>import('./routes/manage/parentManage')
    },
    {
      path:'/upload-parent',
      name:'UploadParent',
      models:()=>[import('./models/parent')],
      component:()=>import('./routes/manage/UploadParent')
    },
    {
      path:'/bluetooth-student-record',
      name:'BluetoothStudentRecord',
      models:()=>[import('./models/bluetooth')],
      component:()=>import('./routes/bluetooth/BluetoothStudentRecord')
    },{
      path:'/bluetooth-teacher-record',
      name:'BluetoothTeacherRecord',
      models:()=>[import('./models/bluetooth')],
      component:()=>import('./routes/bluetooth/BluetoothTeacherRecord')
    },{
      path:'/at-school-statistics',
      name:'AtSchoolStatistics',
      models:()=>[import('./models/bluetooth')],
      component:()=>import('./routes/bluetooth/atSchoolStatistics')
    },{
      path:'/aerial-view-add',
      name:'AerialViewAdd',
      models:()=>[import('./models/dataScreem')],
      component:()=>import('./routes/dataScreem/aerialViewAdd')
    },{
      path:'/sport-statistics',
      name:'SportStatistics',
      models:()=>[import('./models/schedule'), import('./models/lepayHealth')],
      component:()=>import('./routes/lepayHealth/sportStatistics')
    },{
      path:'/health-statistics',
      name:'HealthStatistics',
      models:()=>[import('./models/schedule'), import('./models/lepayHealth')],
      component:()=>import('./routes/lepayHealth/healthStatistics')
    },{
      path:'/evaluate-record',
      name:'EvaluateRecord',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/evaluateRecord')
    },{
      path:'/class-evaluation-group-list',
      name:'ClassEvaluationGroupList',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/classEvaluationGroupList')
    },{
      path:'/evaluation-type-manage',
      name:'EvaluationTypeManage',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/evaluationTypeManage')
    },{
      path:'/add-evaluation-type',
      name:'AddEvaluationType',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/addEvaluationType')
    },{
      path:'/add-evaluation-type2',
      name:'AddEvaluationType2',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/addEvaluationType2')
    },{
      path:'/add-evaluation-type3',
      name:'AddEvaluationType3',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/addEvaluationType3')
    },{
      path:'/add-group',
      name:'addGroup',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/addGroup')
    },{
      path:'/evaluation-flag-detail',
      name:'evaluationFlagDetail',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/evaluationFlagDetail')
    },{
      path:'/week-obtain-list',
      name:'weekObtainList',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/weekObtainList')
    },{
      path:'/obtain-flag-detail',
      name:'obtainFlagDetail',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/obtainFlagDetail')
    },{
      path:'/obtain-flag-detail-week',
      name:'obtainFlagDetailWeek',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/obtainFlagDetailWeek')
    },{
      path:'/add-score-table',
      name:'addScoreTable',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/addScoreTable')
    },{
      path:'/minus-score-table',
      name:'minusScoreTable',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/minusScoreTable')
    },{
      path:'/class-evaluation-type-list',
      name:'classEvaluationTypeList',
      models:()=>[import('./models/evaluate')],
      component:()=>import('./routes/evaluation/classEvaluationTypeList')
    },{
      path:'/custom-type-manage',
      name:'customTypeManage',
      models:()=>[import('./models/teacherDataCollect')],
      component:()=>import('./routes/teacherDataCollect/customTypeManage')
    },{
      path:'/custom-type-detail',
      name:'customTypeDetail',
      models:()=>[import('./models/teacherDataCollect')],
      component:()=>import('./routes/teacherDataCollect/customTypeDetail')
    },{
      path:'/teacher-data-audit',
      name:'TeacherDataAudit',
      models:()=>[import('./models/teacherDataCollect')],
      component:()=>import('./routes/teacherDataCollect/teacherDataAudit')
    },{
      path:'/single-data-audit',
      name:'SingleDataAudit',
      models:()=>[import('./models/teacherDataCollect')],
      component:()=>import('./routes/teacherDataCollect/singleDataAudit')
    },{
      path:'/teacher-info',
      name:'teacherInfo',
      models:()=>[import('./models/teacherDataCollect')],
      component:()=>import('./routes/teacherDataCollect/teacherInfo')
    },{
      path:'/second-upload-staff',
      name:'secondUploadStaff',
      models:()=>[import('./models/person')],
      component:()=>import('./routes/manage/secondUploadStaff')
    },{
      path:'/teacher-info-detail',
      name:'teacherInfoDetail',
      models:()=>[import('./models/person')],
      component:()=>import('./routes/manage/TeacherInfoDetail')
    },{
      path:'/teacher-honor-list',
      name:'TeacherHonorList',
      models:()=>[import('./models/teacherDataCollect')],
      component:()=>import('./routes/teacherDataCollect/teacherHonorList')
    },{
      path:'/teacher-data-check',
      name:'teacherDataCheck',
      models:()=>[import('./models/teacherDataCollect')],
      component:()=>import('./routes/teacherDataCollect/teacherDataCheck')
    },{
      path:'/edit-teacher-data-check',
      name:'editTeacherDataCheck',
      models:()=>[import('./models/teacherDataCollect')],
      component:()=>import('./routes/teacherDataCollect/editTeacherDataCheck')
    },{
      path:'/multi-role-approval-list',
      name:'ApprovalList',
      models:()=>[import('./models/multiRoleApproval')],
      component:()=>import('./routes/multiRoleApproval/approvalList')
    },{
      path:'/multi-role-approval-detail',
      name:'ApprovalDetail',
      models:()=>[import('./models/multiRoleApproval')],
      component:()=>import('./routes/multiRoleApproval/approvalDetail')
    },{
      path:'/vote-list',
      name:'VoteList',
      models:()=>[import('./models/vote')],
      component:()=>import('./routes/voteManage/voteList')
    },{
      path:'/vote-detail',
      name:'VoteDetail',
      models:()=>[import('./models/vote')],
      component:()=>import('./routes/voteManage/voteDetail')
    },{
      path:'/place-list',
      name:'PlaceList',
      models:()=>[import('./models/functionPlaces')],
      component:()=>import('./routes/functionPlaces/placeList')
    },{
      path:'/function-place-detail',
      name:'functionPlaceDetail',
      models:()=>[import('./models/functionPlaces')],
      component:()=>import('./routes/functionPlaces/functionPlaceDetail')
    },{
      path:'/apply-list-index',
      name:'applyListIndex',
      models:()=>[import('./models/functionPlaces')],
      component:()=>import('./routes/functionPlaces/applyListIndex')
    },{
      path:'/apply-detail',
      name:'applyDetail',
      models:()=>[import('./models/functionPlaces')],
      component:()=>import('./routes/functionPlaces/applyDetail')
    },{
      path:'/special-case-manage',
      name:'SpecialCaseManage',
      models:()=>[import('./models/infantSpecialCase')],
      component:()=>import('./routes/infantSpecialCase/specialCaseManage')
    },{
      path:'/special-case-detail',
      name:'SpecialCaseDetail',
      models:()=>[import('./models/infantSpecialCase')],
      component:()=>import('./routes/infantSpecialCase/specialCaseDetail')
    },{
      path:'/special-case-record',
      name:'SpecialCaseRecord',
      models:()=>[import('./models/infantSpecialCase')],
      component:()=>import('./routes/infantSpecialCase/specialCaseRecord')
    },{
      path:'/outside-apply-list',
      name:'OutsideApplyList',
      models:()=>[import('./models/outsideApply')],
      component:()=>import('./routes/outsideApply/outsideApplyList')
    },{
      path:'/outside-apply-detail',
      name:'OutsideApplyDetail',
      models:()=>[import('./models/outsideApply')],
      component:()=>import('./routes/outsideApply/outsideApplyDetail')
    },{
      path:'/outside-apply-record',
      name:'OutsideApplyRecord',
      models:()=>[import('./models/outsideApply')],
      component:()=>import('./routes/outsideApply/outsideApplyRecord')
    },{
      path:'/branch-list',
      name:'branchList',
      models:()=>[import('./models/performance')],
      component:()=>import('./routes/performance/branchList')
    },{
      path:'/branch-detail',
      name:'branchDetail',
      models:()=>[import('./models/performance')],
      component:()=>import('./routes/performance/branchDetail')
    },{
      path:'/branch-upload',
      name:'branchUpload',
      models:()=>[import('./models/performance')],
      component:()=>import('./routes/performance/branchUpload')
    },{
      path:'/import-branch',
      name:'importBranch',
      models:()=>[import('./models/performance')],
      component:()=>import('./routes/performance/importBranch')
    },{
      path:'/branch-achievement-detail',
      name:'branchAchievementDetail',
      models:()=>[import('./models/performance')],
      component:()=>import('./routes/performance/branchAchievementDetail')
    },





    {
      path:'/assess-configuration',
      name:'AssessConfiguration',
      models:()=>[import('./models/teacherAssessment')],
      component:()=>import('./routes/teacherAssessment/assessConfiguration')
    },{
      path:'/assessment-record',
      name:'assessmentRecords',
      models:()=>[import('./models/teacherAssessment')],
      component:()=>import('./routes/teacherAssessment/assessmentRecords')
    },{
      path:'/assessment-detail',
      name:'assessmentDetail',
      models:()=>[import('./models/teacherAssessment')],
      component:()=>import('./routes/teacherAssessment/assessmentDetail')
    },{
      path:'/target-config',
      name:'TargetConfig',
      models:()=>[import('./models/teacherAssessment')],
      component:()=>import('./routes/teacherAssessment/targetConfig')
    },


    //咨询登记
    {
      path:'/consult-register',
      name:'consultRegister',
      models:()=>[import('./models/consultEntrance')],
      component:()=>import('./routes/consultEntrance/consultRegister')
    },

    //参观登记
    {
      path:'/visit-register',
      name:'visitRegister',
      models:()=>[import('./models/consultEntrance')],
      component:()=>import('./routes/consultEntrance/visitRegister')
    },

    //参观登记详情
    {
      path:'/visitRegister-detail',
      name:'visitRegisterDetail',
      models:()=>[import('./models/consultEntrance')],
      component:()=>import('./routes/consultEntrance/visitRegisterDetail')
    },

    //入学申请书
    {
      path:'/entrance-apply',
      name:'entranceApply',
      models:()=>[import('./models/consultEntrance')],
      component:()=>import('./routes/consultEntrance/entranceApply')
    },
    //入学申请书详情
    {
      path:'/entranceApply-detail',
      name:'entranceApplyDetail',
      models:()=>[import('./models/consultEntrance')],
      component:()=>import('./routes/consultEntrance/entranceApplyDetail')
    },
    //自定义表格
    {
      path:'/custom-table',
      name:'customTable',
      models:()=>[import('./models/consultEntrance')],
      component:()=>import('./routes/consultEntrance/customTable')
    },
    //添加自定义表格
    {
      path:'/custom-table-detail',
      name:'addCustomTable',
      models:()=>[import('./models/consultEntrance')],
      component:()=>import('./routes/consultEntrance/addCustomTable')
    },
    {
      path:'/charge-order-list',
      name:'chargeOrderList',
      models:()=>[import('./models/chargeOrder')],
      component:()=>import('./routes/chargeOrder/chargeOrderList')
    },

    {
      path:'/health-register',
      name:'healthRegister',
      models:()=>[import('./models/consultEntrance')],
      component:()=>import('./routes/consultEntrance/healthRegister')
    },
    {
      path:'/health-register-detail',
      name:'healthRegisterDetail',
      models:()=>[import('./models/consultEntrance')],
      component:()=>import('./routes/consultEntrance/healthRegisterDetail')
    },
    {
      path:'/disease-configure',
      name:'diseaseConfigure',
      models:()=>[import('./models/consultEntrance')],
      component:()=>import('./routes/consultEntrance/diseaseConfigure')
    },
    {
      title:"作业管理",
      path:'/task-manage',
      keepalive:true,
      name:'taskManage',
      models:()=>[import('./models/taskManage/taskManage')],
      component:()=>import('./routes/taskManage/taskManage')
    },
    {
      title:"作业详情",
      path:'/task-detail',
      name:'taskDetail',
      models:()=>[import('./models/taskManage/taskManage')],
      component:()=>import('./routes/taskManage/taskDetail')
    },
    {
      title:"学生相册",
      path:'/student-album',
      keepalive:true,
      name:'studentAlbum',
      models:()=>[import('./models/studentAlbum/studentAlbum')],
      component:()=>import('./routes/studentAlbum/studentAlbum')
    },
    {
      title:"学生相册详情",
      path:'/student-album-detail',
      name:'studentAlbumDetail',
      models:()=>[import('./models/studentAlbum/studentAlbum')],
      component:()=>import('./routes/studentAlbum/studentAlbumDetail.js')
    },
    {
      title:"每日健康状况",
      path:'/daily-health-status',
      name:'dailyHealthStatus',
      models:()=>[import('./models/dailyHealthStatus/dailyHealthStatus')],
      component:()=>import('./routes/dailyHealthStatus/dailyHealthStatus')
    },

    {
      path:'/fixed-attendance-rules',
      name:'fixedAttendanceRules',
      title:"固定班制考勤规则",
      models:()=>[import('./models/personnelAttendance/fixedAttendanceRules')],
      component:()=>import('./routes/personnelAttendance/fixedAttendanceRules')
    },
    {
      path:'/schedul-attendance-rules',
      name:'schedulAttendanceRules',
      title:"排版制考勤规则",
      models:()=>[import('./models/personnelAttendance/schedulAttendanceRules')],
      component:()=>import('./routes/personnelAttendance/schedulAttendanceRules')
    },
    {
      path:'/personnel-attendance-statistics',
      name:'personnelAttendanceStatistics',
      title:"人员考勤统计",
      models:()=>[import('./models/personnelAttendance/personnelAttendanceStatistics')],
      component:()=>import('./routes/personnelAttendance/personnelAttendanceStatistics')
    },
    {
      title:"部门考勤统计",
      path:'/department-attendance-statistics',
      name:'departmentAttendanceStatistics',
      keepalive:true,
      models:()=>[import('./models/personnelAttendance/departmentAttendanceStatistics')],
      component:()=>import('./routes/personnelAttendance/departmentAttendanceStatistics')
    },
    {
      title:"部门考勤统计详情",
      path:'/department-attendance-statistics-stu-detail',
      name:'departmentAttendanceStatisticsStuDetail',
      models:()=>[import('./models/personnelAttendance/departmentAttendanceStatistics')],
      component:()=>import('./routes/personnelAttendance/departmentAttendanceStatisticsStuDetail')
    },
    {
      title:"部门考勤统计详情",
      path:'/department-attendance-statistics-teach-detail',
      name:'departmentAttendanceStatisticsTeachDetail',
      models:()=>[import('./models/personnelAttendance/departmentAttendanceStatistics')],
      component:()=>import('./routes/personnelAttendance/departmentAttendanceStatisticsTeachDetail')
    },
    {
      title:"考勤明细",
      path:'/adttendance-details',
      name:'adttendanceDetails',
      keepalive:true,
      models:()=>[import('./models/personnelAttendance/adttendanceDetails')],
      component:()=>import('./routes/personnelAttendance/adttendanceDetails')
    },
    {
      path:'/adttendance-person-details',
      name:'adttendanceDetailsPersonDetail',
      title:"人员考勤明细",
      models:()=>[import('./models/personnelAttendance/adttendanceDetails')],
      component:()=>import('./routes/personnelAttendance/adttendanceDetailsPersonDetail')
    },
    {
      title:"流水记录",
      path:'/adttendance-records',
      name:'adttendanceRecords',
      models:()=>[import('./models/personnelAttendance/adttendanceRecords')],
      component:()=>import('./routes/personnelAttendance/adttendanceRecords')
    },
    {
      title:"意外事件管理",
      path:'/accident-management',
      name:'accidentManagement',
      keepalive:true,
      models:()=>[import('./models/accident/accidentManagement')],
      component:()=>import('./routes/accident/accidentManagement')
    },
    {
      title:"意外事件编辑",
      path:'/accident-management-edit',
      name:'accidentManagementEdit',
      models:()=>[import('./models/accident/accidentManagement')],
      component:()=>import('./routes/accident/accidentManagementEdit')
    },
    {
      title:"意外事件类型",
      path:'/accident-types',
      name:'accidentsTypes',
      keepalive:true,
      models:()=>[import('./models/accident/accidentsTypes')],
      component:()=>import('./routes/accident/accidentsTypes')
    },
    {
      title:"意外事件类型编辑",
      path:'/accident-types-edit',
      name:'accidentsTypesEdit',
      models:()=>[import('./models/accident/accidentsTypes')],
      component:()=>import('./routes/accident/accidentsTypesEdit')
    },
    {
      title:"意外事件统计",
      path:'/accident-statistics',
      name:'accidentStatistics',
      models:()=>[import('./models/accident/accidentStatistics')],
      component:()=>import('./routes/accident/accidentStatistics')
    },

    {
      title:"幼儿活动",
      path:'/childrens-activities',
      name:'childrensActivities',
      keepalive:true,
      models:()=>[import('./models/childrens/childrensActivities')],
      component:()=>import('./routes/childrens/childrensActivities')
    },
    {
      title:"幼儿活动",
      path:'/childrens-activities-edit',
      name:'childrensActivitiesEdit',
      models:()=>[import('./models/childrens/childrensActivities')],
      component:()=>import('./routes/childrens/childrensActivitiesTempEdit')
    },
    {
      title:"推送配置",
      path:'/push-configuration',
      name:'pushConfiguration',
      models:()=>[import('./models/childrens/pushConfiguration')],
      component:()=>import('./routes/childrens/pushConfiguration')
    },

    {
      title:"体检配置",
      path:'/ziling-phyexa',
      name:'zilingPhyexa',
      keepalive:true,
      models:()=>[import('./models/zilingPhyexa/zilingPhyexa')],
      component:()=>import('./routes/zilingPhyexa/zilingPhyexaManage')
    },
    {
      title:"体检查看",
      path:'/ziling-phyexa-view',
      name:'zilingPhyexa',
      models:()=>[import('./models/zilingPhyexa/zilingPhyexa')],
      component:()=>import('./routes/zilingPhyexa/zilingPhyexaManageView')
    },


    // ===================================begin远程门禁=======================
    {
      path:'/door-list',
      name:'doorList',
      keepalive:true,
      models:()=>[import('./models/doorList')],
      component:()=>import('./routes/doormanager/doorList')
    },
    ,{
      path:'/door-new',
      name:'doorNew',
      models:()=>[import('./models/doorList')],
      component:()=>import('./routes/doormanager/doorNew')
    }
    // ===================================end远程门禁=========================

  ]

  return (
    <Router history={history}>
      <AliveScope>
        <Switch>
          <Route path='/login' exact component={LoginPage} />
          <App history={ history }>
            <Switch>
              {
                routes.map(({path,name,keepalive,...others})=>{
                  const Component = dynamic({app,...others});
                  if(keepalive){
                    return (
                      <Route path={path} key={name} exact render={props => {
                        return (
                          <KeepAlive>
                            <ConfigProvider locale={zhCN}>
                              <Component {...props} />
                            </ConfigProvider>
                          </KeepAlive>
                        )}} />
                    )
                  }else{
                    return(
                      <Route path={path} key={name} exact render={props => {
                        return (<Component {...props} params={others.params} />)
                      }} />
                    )
                  }
                })
              }
            </Switch>
          </App>
        </Switch>
      </AliveScope>
    </Router>
  );
}

export default RouterConfig;
